name: Snipbook
options:
  bundleIdPrefix: com.snipbook
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: 5824UP464U
    CODE_SIGN_STYLE: Automatic

targets:
  Snipbook:
    type: application
    platform: iOS
    sources:
      - path: Snipbook/App
      - path: Snipbook/Models
      - path: Snipbook/Views
      - path: Snipbook/Services
      - path: Snipbook/Shapes
      - path: Snipbook/Extensions
      - path: Snipbook/Resources/Assets.xcassets
      - path: Snipbook/Resources/Fonts
        buildPhase: resources
      - path: Snipbook/Resources/PrivacyInfo.xcprivacy
        buildPhase: resources
    info:
      path: Snipbook/Resources/Info.plist
      properties:
        NSCameraUsageDescription: "Snipbook uses your camera to capture photos for your collection."
        NSPhotoLibraryUsageDescription: "Snipbook needs access to your photo library to import images."
        NSPhotoLibraryAddUsageDescription: "Snipbook can save your snips to your photo library."
        NSLocationWhenInUseUsageDescription: "Snipbook saves where you captured each snip so you can remember the location."
        UIAppFonts:
          - Lexend-Regular.ttf
          - Lexend-Medium.ttf
          - Pacifico-Regular.ttf
    settings:
      base:
        INFOPLIST_FILE: Snipbook/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.laurastrandt.snipbook
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: 5824UP464U
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"

schemes:
  Snipbook:
    build:
      targets:
        Snipbook: all
    run:
      config: Debug
    archive:
      config: Release
